-- ============================================================
-- V2: Journal Entries
-- The atomic, immutable financial event record.
-- Once status = 'POSTED', NO field may be mutated.
-- Reversal is the only correction mechanism (creates a new entry).
-- ============================================================

CREATE TYPE journal_entry_status AS ENUM (
    'DRAFT',     -- Being built, not yet committed
    'POSTED',    -- Committed, immutable, affects balances
    'REVERSED'   -- Neutralized by a paired reversal entry
);

CREATE TYPE journal_entry_source AS ENUM (
    'MANUAL',           -- Created directly by ACCOUNTANT/ADMIN
    'SALE',             -- Generated by "Record a Sale" flow
    'EXPENSE',          -- Generated by "Record an Expense" flow
    'PURCHASE',         -- Generated by "I bought something" flow
    'PAYMENT_RECEIVED', -- Customer paid their invoice
    'PAYMENT_MADE',     -- Business paid a supplier
    'PAYROLL',          -- Salary/wage processing
    'ADJUSTMENT',       -- Period-end adjustments
    'AI_SUGGESTED'      -- AI Orchestrator proposed entry (requires ACCOUNTANT approval)
);

CREATE TABLE journal_entries (
    id                  BIGSERIAL               PRIMARY KEY,
    company_id          BIGINT                  NOT NULL,
    entry_number        VARCHAR(30)             NOT NULL,  -- Human-readable: "JE-2024-000001"
    entry_date          DATE                    NOT NULL,  -- Business date (not system date)
    description         TEXT                    NOT NULL,  -- Human-readable narration
    source              journal_entry_source    NOT NULL,
    status              journal_entry_status    NOT NULL DEFAULT 'DRAFT',
    reference_id        BIGINT,                            -- FK to source record (invoice_id, expense_id, etc.)
    reference_type      VARCHAR(50),                       -- "INVOICE", "EXPENSE", etc.
    reversal_of_id      BIGINT                  REFERENCES journal_entries(id),  -- Points to original if this is a reversal
    reversed_by_id      BIGINT                  REFERENCES journal_entries(id),  -- Points to reversal entry
    posted_at           TIMESTAMPTZ,
    posted_by           BIGINT,                            -- user_id who posted
    created_by          BIGINT                  NOT NULL,
    created_at          TIMESTAMPTZ             NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ             NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_entry_number_per_company UNIQUE (company_id, entry_number),
    CONSTRAINT chk_reversal_integrity CHECK (
        -- An entry cannot be its own reversal
        reversal_of_id IS DISTINCT FROM id
    )
);

CREATE INDEX idx_je_company_date     ON journal_entries(company_id, entry_date DESC);
CREATE INDEX idx_je_company_status   ON journal_entries(company_id, status);
CREATE INDEX idx_je_reference        ON journal_entries(reference_type, reference_id);
